# Generated by Django 5.0.6 on 2024-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('interest_rate', models.IntegerField()),
                ('down_payment_dollar', models.DecimalField(decimal_places=3, max_digits=10)),
                ('down_payment_percent', models.IntegerField()),
                ('mortgage_term', models.IntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=3, max_digits=10)),
                ('loan_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_interest_paid', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
